apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicasets
  labels:
    app: myapp-selectorset
spec: 
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template: 
    metadata:
      name: nginx-po
      labels: 
        app: myapp
    spec:
      containers:
        - name: nginx-container
          image: nginx
